---
- name: create ssh key
  user:
    name:             "{{lookup('env', 'USER')}}"
    generate_ssh_key: yes
    ssh_key_bits:     2048
    ssh_key_file:     ".ssh/id_rsa-{{platform}}-{{env}}"

- name: ec2 key
  ec2_key:
    name:         "{{platform}}-{{env}}"
    key_material: "{{item}}"
  with_file: "~/.ssh/id_rsa-{{platform}}-{{env}}.pub"
