---
- name: rancher systemd
  template:
    src:   rancher.service.j2
    dest:  /etc/systemd/system/rancher.service
    owner: root
    group: root
    mode:  0644
  register: rancher_systemd
  become: yes

- name: restart service
  service:
    name:  rancher
    state: restarted
  when: rancher_systemd is changed
  become: yes


- name: rancher service
  service:
    name:  rancher
    state: started
  become: yes

- name: verify rancher is running
  uri:
    url:            "https://localhost"
    status_code:    200
    validate_certs: false
  register: uri_index
  until: uri_index.status|default('404') == 200
  retries: 5
  delay: 30
