---
- name: lookup vpc
  ec2_vpc_net_facts:
    filters:
      "tag:Environment": "{{dyn_vpc_lookup}}"
  register: ec2_vpc_facts

- name: lookup subnets
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ec2_vpc_facts.vpcs[0].id}}"
  register: ec2_subnet_facts

- name: ubuntu 16 ami
  ec2_ami_facts:
    owners: 099720109477
    filters:
      name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
  register: ec2_ami_facts

- name: define desired ami
  set_fact:
    latest_ami: "{{ec2_ami_facts.images|sort(attribute='creation_date')|last}}"

- name: default security group rules
  set_fact:
    security_group_rules: []

- name: add rules for app ports
  set_fact:
    security_group_rules: >
      {{security_group_rules}} +
      [
        {
          'proto': 'tcp',
          'from_port': '{{dyn_farm_port_exposed}}',
          'to_port': '{{dyn_farm_port_exposed}}',
          'cidr_ip': '{{item|ipsubnet(16)}}'
        }
      ]
  with_items: "{{ansible_all_ipv4_addresses}}"

- name: add rules for ssh
  set_fact:
    security_group_rules: >
      {{security_group_rules}} +
      [
        { 'proto': 'tcp', 'from_port': '22', 'to_port': '22', 'cidr_ip': '{{item|ipsubnet(16)}}' }
      ]
  with_items: "{{ansible_all_ipv4_addresses}}"
