---
- name: ubuntu 16 ami
  ec2_ami_find:
    name:       "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
    owner:      099720109477
    sort:       name
    sort_order: descending
    sort_end:   1
  register: ami_find

- name: security group
  ec2_group:
    name:        "{{platform}}-{{env}}-farm"
    description: "{{platform}} farm access for {{env}}"
    vpc_id:      "{{ec2_vpc_facts.vpcs[0].id}}"
    rules:       "{{security_group_rules}}"

- name: lookup ec2 instance
  ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:environment":   "{{env}}"
      "tag:platform":      "{{platform}}"
      "tag:service":       farm
  register: ec2_facts

- name: ec2 instance
  ec2:
    key_name:         "{{platform}}-{{env}}"
    group:            "{{platform}}-{{env}}-farm"
    instance_type:    t2.small
    image:            "{{ami_find.results[0].ami_id}}"
    wait:             yes
    instance_tags:
       environment: "{{env}}"
       platform:    "{{platform}}"
       service:     farm
       name:        "{{platform}}-{{env}}-farm"
    volumes:
      - device_name:           /dev/sda1
        volume_size:           "{{dyn_farm_disk_size}}"
        delete_on_termination: true
    vpc_subnet_id:    "{{ec2_subnet_facts|json_query('subnets[*].id')|random}}"
    assign_public_ip: no
  register: ec2_instance
  when: ec2_facts.instances|length < 1

- name: clear cache
  shell: "AWS_PROFILE={{lookup('env','AWS_PROFILE')}} ./inventory/ec2.py --refresh-cache"
  when: ec2_instance|changed

- name: wait for host to be available
  wait_for:
    host:    "{{ec2_instance.instances[0].private_ip}}"
    port:    22
    timeout: 60
  when: ec2_instance|changed

- name: clear cache
  shell: "AWS_PROFILE={{lookup('env','AWS_PROFILE')}} ./inventory/ec2.py --refresh-cache"
  register: shell_refresh_cache
  until: "ec2_instance.instances[0].private_ip in (shell_refresh_cache['stdout']|from_json)['ec2']"
  retries: 6
  delay: 30
  when: ec2_instance|changed

- name: refresh meta
  meta: refresh_inventory

